name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        run: sudo apt-get install -y nodejs
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
      - name: Deploy application
        run: gh pages -d build
